# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in ree_lib.gemspec
gemspec

gem "rake", "~> 13.0"

group :test do
  gem 'rspec'
  gem 'bootsnap'
  gem 'webmock'
  gem 'faker'
end