#!/usr/bin/env ruby
# -*- encoding: utf-8 -*-

require "rubygems"
require "bundler/setup"
require "ree"

Ree.init(
  File.expand_path(
    File.join(__dir__, "../lib/ree_spec" )
  )
)

package_require "ree_spec_cli/run_command"
ReeSpecCli::RunCommand.new.call