name: Testing

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - main

jobs:
  rspec:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        ruby: ['3.2', '3.3', '3.4']
        gemfile_folders: ['ree', 'ree_lib', 'ree_spec', 'ruby-lsp-ree']
        include:
          - gemfile_folders: 'ree'
            rspec_cmd: 'cd ree && bundle exec rspec'
          - gemfile_folders: 'ree_lib'
            rspec_cmd: 'cd ree_lib/lib/ree_lib && bundle exec ree spec'
          - gemfile_folders: 'ree_spec'
            rspec_cmd: 'cd ree_spec/lib/ree_spec && bundle exec ree spec'
          - gemfile_folders: 'ruby-lsp-ree'
            rspec_cmd: 'cd ruby-lsp-ree && bundle exec rspec'

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
          working-directory: ${{ matrix.gemfile_folders }}
      - run: ${{ matrix.rspec_cmd }}